#!/usr/bin/env bash
# audio-route.sh — send this machine's audio to the other machine (PC <-> laptop)
# or bring it back to the local speakers/headphones.
#
#   audio-route.sh local    -> output on this machine's own hardware
#   audio-route.sh send     -> stream this machine's audio to the other machine
#   audio-route.sh status   -> prints "local" or "send"
#
# Run by the sender over SSH on the other machine:
#   audio-route.sh receive <from>   -> start the RTP receiver
#   audio-route.sh receive-stop     -> stop it
#
# Mechanism: RTP. The sender runs a small PipeWire instance with module-rtp-sink
# (a sink named send_to_other); the receiver runs one with module-rtp-source,
# played into its default output. Only the receiver corrects the clock drift
# between both machines. The old pulse tunnel corrected it on both ends, and the
# two controllers fought until a "bubbling" noise filled the audio over time.
#
# The receiver needs UDP $RTP_PORT open:
#   sudo ufw allow from 192.168.0.0/16 to any port 46000 proto udp comment 'audio-route rtp'

set -euo pipefail

# ── config ──────────────────────────────────────────────────────────────────
PC_HOST="CachyOS-PC"      ; PC_ADDR="CachyOS-PC.local"
LT_HOST="CachyOS-Laptop"  ; LT_ADDR="CachyOS-Laptop.local"
SEND_SINK="send_to_other"
RECV_NODE="audio_route_receive"
RTP_PORT=46000
# Audio the receiver keeps buffered. It has to exceed the delay of its output: a
# Bluetooth sink adds ~190 ms, and below that the receiver discards everything.
LATENCY_MSEC="${AUDIO_ROUTE_LATENCY:-300}"
# -n: never read stdin, so a call nested in another SSH session can't swallow it
SSH=(ssh -n -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new)
REMOTE_SCRIPT='~/.config/ags/scripts/audio-route.sh'
RUN_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
SEND_CONF="$RUN_DIR/audio-route-send.conf"
RECV_CONF="$RUN_DIR/audio-route-recv.conf"

# ── resolve the "other" machine ─────────────────────────────────────────────
me="$(hostname)"
case "$me" in
  "$PC_HOST") other_addr="$LT_ADDR" ;;
  "$LT_HOST") other_addr="$PC_ADDR" ;;
  *) echo "audio-route: unknown host '$me'" >&2; exit 1 ;;
esac
other="${other_addr%%.*}"

other_ipv4() {
  getent ahostsv4 "$other_addr" 2>/dev/null | awk 'NR==1{print $1}'
}

move_all_inputs() {
  local target="$1" id
  pactl list sink-inputs short | cut -f1 | while read -r id; do
    [ -n "$id" ] && pactl move-sink-input "$id" "$target" 2>/dev/null || true
  done
}

# the pulse tunnel used before RTP, in case one is still loaded
unload_legacy_tunnel() {
  pactl list modules short \
    | awk -v k="sink_name=$SEND_SINK" 'index($0,k){print $1}' \
    | while read -r m; do pactl unload-module "$m" 2>/dev/null || true; done
}

fail() {
  notify-send -a "Audio" "No se pudo enviar el audio" "$1" 2>/dev/null || true
  echo "audio-route: $1" >&2
  exit "${2:-1}"
}

# ── PipeWire instances (one per config file) ───────────────────────────────
instance_pids() {
  pgrep -a pipewire | awk -v c="-c $1" 'index($0, c){print $1}'
}

stop_instance() {
  local conf="$1" pid i
  for pid in $(instance_pids "$conf"); do kill "$pid" 2>/dev/null || true; done
  for i in $(seq 1 20); do
    [ -z "$(instance_pids "$conf")" ] && return 0
    sleep 0.1
  done
}

start_instance() {
  stop_instance "$1"
  setsid -f pipewire -c "$1" >/dev/null 2>&1 </dev/null
}

write_send_conf() {
  local ip="$1"
  cat > "$SEND_CONF" <<EOF
# Generated by audio-route.sh: RTP sender towards $other
context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}
context.modules = [
    { name = libpipewire-module-rt, args = { nice.level = -11 }, flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-rtp-sink
        args = {
            destination.ip   = "$ip"
            destination.port = $RTP_PORT
            sess.name        = "audio-route $me"
            audio.format     = "S16BE"
            audio.rate       = 48000
            audio.channels   = 2
            audio.position   = [ FL FR ]
            stream.props = {
                media.class      = "Audio/Sink"
                node.name        = "$SEND_SINK"
                node.description = "Enviar a $other"
            }
        }
    }
]
EOF
}

write_recv_conf() {
  local from="$1"
  cat > "$RECV_CONF" <<EOF
# Generated by audio-route.sh: RTP receiver for audio sent by $from
context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}
context.modules = [
    { name = libpipewire-module-rt, args = { nice.level = -11 }, flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-rtp-source
        args = {
            source.ip         = "0.0.0.0"
            source.port       = $RTP_PORT
            sess.latency.msec = $LATENCY_MSEC
            stream.may-pause  = true
            audio.format      = "S16BE"
            audio.rate        = 48000
            audio.channels    = 2
            audio.position    = [ FL FR ]
            stream.props = {
                # a playback stream, so wireplumber links it to the default output
                media.class      = "Stream/Output/Audio"
                node.name        = "$RECV_NODE"
                node.description = "Audio de $from"
                media.name       = "Audio de $from"
            }
        }
    }
]
EOF
}

sink_ready() {
  pactl list sinks short | awk '{print $2}' | grep -qx "$SEND_SINK"
}

# ── commands ────────────────────────────────────────────────────────────────
cmd_local() {
  local def="" i was_sending=""
  # unpin the output instead of pinning a local one: with no configured choice wireplumber
  # picks by priority, so it keeps switching to bluetooth headphones whenever they connect
  pw-metadata -n default -d 0 default.configured.audio.sink >/dev/null 2>&1 || true
  [ -n "$(instance_pids "$SEND_CONF")" ] && was_sending=1
  stop_instance "$SEND_CONF"
  unload_legacy_tunnel
  # otherwise the other machine's receiver keeps listening for nothing
  if [ -n "$was_sending" ]; then
    "${SSH[@]}" "emerson@$other_addr" "bash $REMOTE_SCRIPT receive-stop" >/dev/null 2>&1 || true
  fi
  for i in $(seq 1 20); do
    def="$(pactl get-default-sink)"
    [ -n "$def" ] && [ "$def" != "$SEND_SINK" ] && break
    sleep 0.1
  done
  if [ -z "$def" ] || [ "$def" = "$SEND_SINK" ]; then
    echo "audio-route: no local output sink found" >&2
    exit 1
  fi
  echo "local:$def"
}

cmd_send() {
  local ip remote_sink i
  ip="$(other_ipv4)"
  [ -z "$ip" ] && fail "No se encontró la dirección de $other en la red. ¿Está encendida?"

  # 1. find the receiver's current output
  remote_sink="$("${SSH[@]}" "emerson@$other_addr" 'pactl get-default-sink' 2>/dev/null)" || remote_sink=""
  [ -z "$remote_sink" ] && fail "No hay conexión por SSH con $other. ¿Está encendida?"
  # the receiver is already sending to us: sending back would loop the audio between both
  [ "$remote_sink" = "$SEND_SINK" ] && fail "$other ya te está enviando su audio. Detén ese envío primero." 2

  # 2. start the receiver there
  "${SSH[@]}" "emerson@$other_addr" "bash $REMOTE_SCRIPT receive $me" >/dev/null 2>&1 \
    || fail "No se pudo preparar la recepción de audio en $other."

  # 3. start the sender here and move everything to it
  unload_legacy_tunnel
  write_send_conf "$ip"
  start_instance "$SEND_CONF"
  for i in $(seq 1 30); do sink_ready && break; sleep 0.1; done
  if ! sink_ready; then
    stop_instance "$SEND_CONF"
    fail "No se pudo crear la salida de audio hacia $other."
  fi
  pactl set-default-sink "$SEND_SINK"
  move_all_inputs "$SEND_SINK"

  echo "send:$other_addr:$remote_sink"
}

cmd_receive() {
  local from="${1:-la otra máquina}" i
  write_recv_conf "$from"
  start_instance "$RECV_CONF"
  for i in $(seq 1 30); do
    pw-cli ls Node 2>/dev/null </dev/null | grep -q "\"$RECV_NODE\"" && break
    sleep 0.1
  done
  if ! pw-cli ls Node 2>/dev/null </dev/null | grep -q "\"$RECV_NODE\""; then
    stop_instance "$RECV_CONF"
    echo "audio-route: the RTP receiver did not start" >&2
    exit 1
  fi
  echo "receive:$from"
}

cmd_receive_stop() {
  stop_instance "$RECV_CONF"
  echo "receive-stop"
}

cmd_status() {
  if [ "$(pactl get-default-sink)" = "$SEND_SINK" ]; then echo "send"; else echo "local"; fi
}

case "${1:-status}" in
  local)        cmd_local ;;
  send)         cmd_send ;;
  status)       cmd_status ;;
  receive)      cmd_receive "${2:-}" ;;
  receive-stop) cmd_receive_stop ;;
  *) echo "usage: $(basename "$0") {local|send|status}" >&2; exit 1 ;;
esac
